"""Shared types and protocols for tick-spatial."""
from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from tick import World


@dataclass
class Pos2D:
    x: float
    y: float


class SpatialIndex(Protocol):
    def place(self, eid: int, x: int, y: int) -> None: ...
    def move(self, eid: int, x: int, y: int) -> None: ...
    def remove(self, eid: int) -> None: ...
    def at(self, x: int, y: int) -> frozenset[int]: ...
    def position_of(self, eid: int) -> tuple[int, int] | None: ...
    def in_radius(self, x: int, y: int, r: int) -> list[tuple[int, int, int]]: ...
    def neighbors(self, x: int, y: int) -> list[tuple[int, int]]: ...
    def heuristic(self, a: tuple[int, int], b: tuple[int, int]) -> float: ...
    def tracked_entities(self) -> frozenset[int]: ...
    def rebuild(self, world: World) -> None: ...
